name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Create Maven settings.xml
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
                "id": "github-packages",
                "username": "${{ secrets.USER_PACKAGE_READ }}",
                "password": "${{ secrets.TOKEN_PACKAGE_READ }}"
            }]
      - name: Maven Build
        run: mvn clean install
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: proxy-generator
          path: target/proxy-generator-0.2.0-SNAPSHOT-jar-with-dependencies.jar
